[package]
name = "rustie"
version = "0.1.0"
edition = "2021"

[lib]
name         = "rustie"
crate-type   = ["rlib", "cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12"
libc = "0.2"
