[tools]
pipenv = "2023.10.3"
poetry = "1.5.1"
crystal = "1.11.2"
ruby = "2.7.8"
go = "1.20.4"
haskell = "9.8.1"
python = "3.10.12" # must be after pipenv so the pipenv bin is first in PATH
rust = "1.72.1"
nim = "2.0.2"
julia = "1.10.4"
zig = "0.13.0"
